/** The review screen page: shared by the review build and the browser runner (which opens it with a packet). */
export const CSS = `:root{--bg:#f6f7f9;--card:#fff;--ink:#16202b;--muted:#5b6876;--line:#d9dee5;--accent:#1f5fbf;--accent-ink:#fff;--good:#1c7c4a;--warn:#a35a00;--bad:#b42318;--soft:#eef3fb;--rec:#8a96a3;--prop:#1f5fbf;--staff:#1c7c4a;--band:rgba(31,95,191,.12)}
@media (prefers-color-scheme:dark){:root{--bg:#0f141a;--card:#161d25;--ink:#e6ebf1;--muted:#9aa7b4;--line:#2a3542;--accent:#6ea2ff;--accent-ink:#0b1220;--good:#5fd394;--warn:#f0b35a;--bad:#ff7b72;--soft:#1b2633;--rec:#7f8b98;--prop:#6ea2ff;--staff:#5fd394;--band:rgba(110,162,255,.16)}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14.5px/1.45 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}main{max-width:1060px;margin:0 auto;padding:18px 16px 80px}
h1{font-size:20px;margin:0}.muted{color:var(--muted)}.small{font-size:12.5px}button{font:inherit;font-weight:600;border-radius:7px;border:1px solid var(--line);background:var(--card);color:var(--ink);padding:6px 12px;cursor:pointer}button.primary{background:var(--accent);border-color:var(--accent);color:var(--accent-ink)}button.link{border:0;background:none;color:var(--accent);text-decoration:underline}button:disabled{opacity:.45;cursor:not-allowed}
input,select{font:inherit;color:inherit;background:var(--bg);border:1px solid var(--line);border-radius:6px;padding:5px 8px}
.bar{position:sticky;top:0;z-index:2;background:var(--bg);padding:10px 0;border-bottom:1px solid var(--line);display:flex;flex-wrap:wrap;gap:10px;align-items:center}progress{width:160px}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:12px 14px;margin-top:12px}.card.done{border-left:4px solid var(--good)}
.card header{display:flex;flex-wrap:wrap;gap:8px;align-items:baseline}.ord{color:var(--muted);font-size:12px}.chg{margin-left:auto;font-weight:700}.chg.big{color:var(--bad)}.chg.mid{color:var(--warn)}.chg.small{color:var(--muted)}
.state{font-size:12px;padding:1px 8px;border-radius:999px;background:var(--soft)}.state[data-s=approve]{color:var(--good)}.state[data-s=edit]{color:var(--warn)}.state[data-s=reject]{color:var(--bad)}
.grid{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(0,1fr);gap:14px;margin-top:6px}@media(max-width:760px){.grid{grid-template-columns:1fr}}svg{width:100%;height:auto}
.rec{fill:none;stroke:var(--rec);stroke-width:1.6;stroke-dasharray:4 3}.prop{fill:none;stroke:var(--prop);stroke-width:2.2}.staff{fill:none;stroke:var(--staff);stroke-width:1.6}.band{fill:var(--band);stroke:none}.t{fill:var(--muted);font-size:10px}
.legend{font-size:11.5px;color:var(--muted);display:flex;flex-wrap:wrap;gap:10px}.k{display:inline-block;width:14px;height:3px;vertical-align:middle;margin-right:3px}.k.rec{background:var(--rec)}.k.prop{background:var(--prop)}.k.staff{background:var(--staff)}.k.band{background:var(--band);height:8px}
ul{margin:4px 0;padding-left:18px}.avg{margin:0}.actions{display:flex;gap:8px;margin-top:8px}form[hidden]{display:none}form{display:flex;flex-wrap:wrap;gap:8px;align-items:end;margin-top:8px;padding:8px;background:var(--soft);border-radius:8px}form label{display:flex;flex-direction:column;font-size:12px;gap:2px}form .wide{flex:1;min-width:220px}
.sign{margin-top:22px;background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px;display:flex;flex-wrap:wrap;gap:10px;align-items:end}.loader{margin-top:40px;text-align:center}`;
export const BODY = `<main><div class="loader" id="loader"><h1>Owner review</h1><p class="muted">Load today's review packet (plumb.review/1).</p><input type="file" id="file" accept=".json,application/json"></div>
<div id="app" hidden><h1 id="title"></h1><p class="muted" id="meta"></p>
<div class="bar"><progress id="prog" value="0" max="1"></progress><span id="count"></span><label>Product <select id="fProduct"><option value="">all</option><option>A</option><option>C</option><option>D</option><option>E</option></select></label><label><input type="checkbox" id="fMoved"> only gates that moved ≥1%</label><button id="bulk">Approve all within 1% of record (<span id="bulkN">0</span>)</button></div>
<div id="cards"></div>
<section class="sign"><label>Your name <input id="name"></label><label>Role <input id="role" placeholder="forecast owner"></label><button id="sign" class="primary" disabled>Sign and download decisions</button><span class="muted" id="signHint"></span></section>
<p class="muted small">Nothing is published from this screen. The signed decisions file goes to the publish step, which refuses an unsigned, incomplete or stale review. Synthetic data.</p></div></main>`;
export const page = (js: string, packet?: string) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Owner review</title><style>${CSS}</style></head><body>${BODY}${packet ? `<script>window.PACKET=${packet.replace(/</g, "\\u003c")};</script>` : ""}<script>${js}</script></body></html>\n`;
