#!/usr/bin/env bun
/**
 * PLUMB command line.
 *
 *   bun run Tools/run.ts ingest   --book demo --source planner-mtd [--source roster-summary]
 *   bun run Tools/run.ts model    --book demo
 *   bun run Tools/run.ts simulate --book demo [--draws 20000]
 *   bun run Tools/run.ts report   --book demo
 *
 * Orchestration only. All staffing arithmetic lives in Tools/engine/ (Python) --
 * see docs/ENGINE.md for why that boundary exists and why it should stay.
 */

import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { applyMapping, loadMapping, toCsv, type Gap, type MapResult } from "./map.ts";

const ROOT = join(import.meta.dir, "..");
const ENGINE = join(ROOT, "Tools/engine");

// ------------------------------------------------------------------------- args

function parseArgs(argv: string[]) {
  const cmd = argv[0];
  const flags: Record<string, string[]> = {};
  for (let i = 1; i < argv.length; i++) {
    if (!argv[i].startsWith("--")) continue;
    const key = argv[i].slice(2);
    const val = argv[i + 1]?.startsWith("--") === false ? argv[++i] : "true";
    (flags[key] ??= []).push(val);
  }
  return { cmd, flags };
}
const one = (f: Record<string, string[]>, k: string, d?: string) => f[k]?.[0] ?? d;

/**
 * Prefer the engine venv; fall back to system python when it already has the deps.
 *
 * Existence is not the test — a half-built venv (interpreter present, site-packages
 * empty) will shadow a perfectly good system python and fail with a confusing
 * ModuleNotFoundError. So we ask each candidate whether it can actually import what
 * the engine needs, and say plainly when neither can.
 */
let _python: string | undefined;
function python(): string {
  if (_python) return _python;
  const probe = "import numpy, pandas, scipy, yaml";
  for (const cand of [join(ENGINE, ".venv/bin/python"), "python3"]) {
    if (cand.includes(".venv") && !existsSync(cand)) continue;
    if (spawnSync(cand, ["-c", probe], { encoding: "utf8" }).status === 0)
      return (_python = cand);
  }
  die(
    "no Python interpreter with the engine dependencies.\n" +
    `  Install them:  python3 -m venv ${ENGINE}/.venv && ` +
    `${ENGINE}/.venv/bin/pip install -r ${ENGINE}/requirements.txt\n` +
    "  (needs python3-venv; see docs/ENGINE.md)",
  );
}

function runPython(code: string): { ok: boolean; out: string } {
  const r = spawnSync(python(), ["-c", code], { cwd: ENGINE, encoding: "utf8" });
  const out = (r.stdout ?? "") + (r.stderr ?? "");
  return { ok: r.status === 0, out };
}

// ----------------------------------------------------------------------- ingest

function writeGapRegister(bookDir: string, results: MapResult[]) {
  const rows: (Gap & { source: string })[] = results.flatMap((r) =>
    r.gaps.map((g) => ({ ...g, source: r.mapping.source })));

  const body = rows.length === 0
    ? "_No gaps. Every canonical column is filled and every source column is accounted for._\n"
    : `| Input | Status | Current treatment | Source | Variance share | Rank |
|---|---|---|---|---|---|
${rows.map((g) =>
  `| \`${g.input}\` | ${g.status} | ${g.treatment} | ${g.source} | not yet run | — |`).join("\n")}
`;

  const md = `# Intake gaps — ${bookDir.split("/").pop()}

_Generated by \`run.ts ingest\` on ${new Date().toISOString().slice(0, 10)}._

Every input PLUMB needs and does not have. **Rank by variance contribution per unit of effort to
obtain**, not by how badly the input is missed — see \`context/plumb/GAP-REGISTER.md\`.

Variance share comes from \`mc_staffing.attribution()\` and is populated once the simulation has
run. Until then these are unranked: the list is complete, the priority is not.

${body}
## Reading this

- **absent** — the column is not in the document. Honest and easy to flag.
- **unmapped source column** — the document has it and the mapping does not use it. Either add it
  to \`columns\` or declare it in \`unmapped_ok\`. This is how a new column in next month's export
  gets noticed instead of silently dropped.
- **proxy** — something is standing in. The most dangerous status, because the output looks
  complete.
- **disputed definition** — the number exists but two parties mean different things by it.

**This is not a backlog to clear.** A model with a documented gap register is more trustworthy
than one without. Present it alongside the first model output, never as a reason to delay one.
`;
  writeFileSync(join(bookDir, "02-canonical", "INTAKE-GAPS.md"), md);
}

function ingest(flags: Record<string, string[]>) {
  const book = one(flags, "book") ?? die("--book is required");
  const bookDir = join(ROOT, "books", book);
  const sources = flags.source ?? autodetectSources(bookDir);

  mkdirSync(join(bookDir, "02-canonical"), { recursive: true });
  console.log(`\nINGEST — ${book}\n${"=".repeat(64)}`);

  const results: MapResult[] = [];
  let halted = false;

  for (const source of sources) {
    const mapping = loadMapping(bookDir, source);
    const res = applyMapping(bookDir, mapping);
    results.push(res);

    const outName = mapping.kind === "demand" ? "daily_demand.csv" : "daily_supply.csv";
    writeFileSync(join(bookDir, "02-canonical", outName), toCsv(res.columns, res.rows));

    console.log(`\n  ${source}  (${mapping.kind})`);
    console.log(`    rows            ${res.rows.length}`);
    console.log(`    columns filled  ${res.filled} of ${res.total}`);
    console.log(`    gaps            ${res.gaps.length}`);
    console.log(`    -> 02-canonical/${outName}`);

    for (const e of res.errors.slice(0, 5)) console.log(`    ERROR  ${e}`);
    if (res.errors.length) halted = true;

    // A missing REQUIRED column halts before any number is computed.
    const missingRequired = res.gaps.filter((g) => g.treatment.startsWith("REQUIRED"));
    for (const g of missingRequired) console.log(`    HALT   required column absent: ${g.input}`);
    if (missingRequired.length) halted = true;
  }

  writeGapRegister(bookDir, results);
  console.log(`\n  -> 02-canonical/INTAKE-GAPS.md`);

  if (halted) {
    console.log(`\n  INGEST HALTED — see errors above. No model will run on this.\n`);
    process.exit(1);
  }

  // Validation is the engine's job: intake.py owns the rules, so there is one
  // implementation of them rather than a TypeScript paraphrase that drifts.
  console.log(`\n  Validating (intake.py)...`);
  const canon = join(bookDir, "02-canonical").replace(/\\/g, "/");
  const params = join(bookDir, "00-profile/params.yaml").replace(/\\/g, "/");
  const { ok, out } = runPython(`
import sys, yaml, intake
cfg = yaml.safe_load(open("${params}"))
d, s, e = intake.load_intake("${canon}", cfg)
fails = intake.validate(d, s, cfg)
advs  = intake.advisories(d, cfg)
print(f"    rows: demand {len(d)}, supply {len(s)}, events {0 if e is None else len(e)}")
print("    VALIDATION: " + ("PASS" if not fails else f"FAIL ({len(fails)})"))
for f in fails[:10]: print("      -", f)
print(f"    advisories: {len(advs)}")
for a in advs[:5]: print("      -", a)
sys.exit(1 if fails else 0)
`);
  console.log(out.trimEnd());
  console.log(`\n${"=".repeat(64)}`);
  console.log(ok ? "  INGEST COMPLETE\n" : "  INGEST COMPLETE — VALIDATION FAILED\n");
  if (!ok) process.exit(1);
}

function autodetectSources(bookDir: string): string[] {
  const dir = join(bookDir, "mappings");
  if (!existsSync(dir)) die(`no mappings/ in ${bookDir} — write one first, see context/plumb/MAPPING-CONVENTION.md`);
  const found = readdirSync(dir).filter((f) => f.endsWith(".yaml")).map((f) => f.slice(0, -5));
  if (!found.length) die("no mapping files found");
  return found;
}

// ------------------------------------------------------------------------ model

function model(flags: Record<string, string[]>) {
  const book = one(flags, "book") ?? die("--book is required");
  const bookDir = join(ROOT, "books", book);
  mkdirSync(join(bookDir, "03-model"), { recursive: true });

  const canon = join(bookDir, "02-canonical").replace(/\\/g, "/");
  const params = join(bookDir, "00-profile/params.yaml").replace(/\\/g, "/");
  const out = join(bookDir, "03-model/deterministic.csv").replace(/\\/g, "/");

  console.log(`\nMODEL — ${book} (deterministic, daily)\n${"=".repeat(64)}`);

  const r = runPython(`
import yaml, pandas as pd, intake, deterministic
cfg = yaml.safe_load(open("${params}"))
d, s, _ = intake.load_intake("${canon}", cfg)
plan = deterministic.run(d, s, cfg)
plan.to_csv("${out}", index=False)

day = deterministic.daily_summary(plan)
req, dlv = plan.required_h.sum(), plan.delivered_h.sum()
grade = plan.grade.mode()[0]

print(f"    rows                  {len(plan)}")
print(f"    required productive   {req:,.0f} h  [{grade}]")
print(f"    delivered productive  {dlv:,.0f} h  [C]")
print(f"    gap                   {dlv - req:,.0f} h   ({plan.gap_fte.sum() / len(day):,.1f} FTE/day avg)")
print(f"    days short            {(day.gap_h < 0).sum()} of {len(day)}")
worst = day.loc[day.gap_h.idxmin()]
print(f"    worst day             {pd.Timestamp(worst.date).date()}  {worst.gap_fte:,.1f} FTE  ({worst.gap_h:,.0f} h)")
print()
print("    occupancy basis, by channel:")
for ch in sorted(plan.channel.unique()):
    sub = plan[plan.channel == ch]
    print(f"      {ch:6s} {sub.target_occupancy.mean():.3f}  [{sub.grade.mode()[0]}]")
print()
print("    monthly:")
m = plan.assign(month=pd.to_datetime(plan.date).dt.strftime("%Y-%m")).groupby("month").agg(
    required_h=("required_h","sum"), delivered_h=("delivered_h","sum"), gap_h=("gap_h","sum"))
for mo, row in m.iterrows():
    print(f"      {mo}  required {row.required_h:9,.0f}  delivered {row.delivered_h:9,.0f}  gap {row.gap_h:+9,.0f} h")
`);
  console.log(r.out.trimEnd());
  console.log(`\n  -> 03-model/deterministic.csv`);
  console.log(`\n${"=".repeat(64)}`);
  console.log(r.ok ? "  MODEL COMPLETE\n" : "  MODEL FAILED\n");
  if (!r.ok) process.exit(1);
}

// ------------------------------------------------------------------------ stubs

function notYet(cmd: string): never {
  console.log(`\n  "${cmd}" is not wired yet.\n`);
  process.exit(2);
}

// -------------------------------------------------------------------------- main

function die(msg: string): never {
  console.error(`\n  error: ${msg}\n`);
  process.exit(1);
}

const USAGE = `
PLUMB — deterministic + probabilistic staffing engine

  bun run Tools/run.ts ingest   --book <book> [--source <name>]...
  bun run Tools/run.ts model    --book <book>
  bun run Tools/run.ts simulate --book <book> [--draws <n>]
  bun run Tools/run.ts report   --book <book>

  --source may be repeated. Omitted, every mapping in the book is applied.
`;

const { cmd, flags } = parseArgs(process.argv.slice(2));
switch (cmd) {
  case "ingest":   ingest(flags); break;
  case "model":    model(flags); break;
  case "simulate": notYet("simulate"); break;
  case "report":   notYet("report"); break;
  default:         console.log(USAGE); process.exit(cmd ? 1 : 0);
}
